// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/v1/acl.proto

package entityv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ACL.
type ACL struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACL) Reset()         { *m = ACL{} }
func (m *ACL) String() string { return proto.CompactTextString(m) }
func (*ACL) ProtoMessage()    {}
func (*ACL) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4042320e5bdcad6, []int{0}
}

func (m *ACL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACL.Unmarshal(m, b)
}
func (m *ACL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACL.Marshal(b, m, deterministic)
}
func (m *ACL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACL.Merge(m, src)
}
func (m *ACL) XXX_Size() int {
	return xxx_messageInfo_ACL.Size(m)
}
func (m *ACL) XXX_DiscardUnknown() {
	xxx_messageInfo_ACL.DiscardUnknown(m)
}

var xxx_messageInfo_ACL proto.InternalMessageInfo

func (m *ACL) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ACL)(nil), "cc.entity.v1.ACL")
}

func init() { proto.RegisterFile("entity/v1/acl.proto", fileDescriptor_a4042320e5bdcad6) }

var fileDescriptor_a4042320e5bdcad6 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xcd, 0x2b, 0xc9,
	0x2c, 0xa9, 0xd4, 0x2f, 0x33, 0xd4, 0x4f, 0x4c, 0xce, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x49, 0x4e, 0xd6, 0x83, 0x88, 0xeb, 0x95, 0x19, 0x2a, 0x89, 0x72, 0x31, 0x3b, 0x3a, 0xfb,
	0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6,
	0x38, 0xf9, 0x70, 0x09, 0x24, 0xe7, 0xe7, 0xea, 0x21, 0x2b, 0x75, 0xe2, 0x70, 0x4c, 0xce, 0x09,
	0x00, 0x19, 0x11, 0xc0, 0x18, 0xc5, 0x01, 0x11, 0x2e, 0x33, 0x5c, 0xc4, 0xc4, 0xec, 0xec, 0x1a,
	0xb1, 0x8a, 0x89, 0xc7, 0x39, 0x59, 0xcf, 0x15, 0xa2, 0x34, 0xcc, 0xf0, 0x14, 0x88, 0x1b, 0x03,
	0xe1, 0xc6, 0x84, 0x19, 0x26, 0xb1, 0x81, 0x6d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2,
	0xc7, 0xd0, 0x38, 0x90, 0x00, 0x00, 0x00,
}
