// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/v1/asset.proto

package entityv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Asset.
type Asset struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AclTag               string         `protobuf:"bytes,2,opt,name=acl_tag,json=aclTag,proto3" json:"acl_tag,omitempty"`
	MerchantId           string         `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DescribeUrl          string         `protobuf:"bytes,4,opt,name=describe_url,json=describeUrl,proto3" json:"describe_url,omitempty"`
	Price                int64          `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Meta                 *AssetMetaInfo `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	CreatedAt            int64          `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15fd74ac3c1b80, []int{0}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetAclTag() string {
	if m != nil {
		return m.AclTag
	}
	return ""
}

func (m *Asset) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Asset) GetDescribeUrl() string {
	if m != nil {
		return m.DescribeUrl
	}
	return ""
}

func (m *Asset) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Asset) GetMeta() *AssetMetaInfo {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Asset) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// AssetMetaInfo.
type AssetMetaInfo struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	CoverImageUrl        string   `protobuf:"bytes,2,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Teaser               string   `protobuf:"bytes,5,opt,name=teaser,proto3" json:"teaser,omitempty"`
	Slug                 string   `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	EventUrl             string   `protobuf:"bytes,7,opt,name=event_url,json=eventUrl,proto3" json:"event_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetMetaInfo) Reset()         { *m = AssetMetaInfo{} }
func (m *AssetMetaInfo) String() string { return proto.CompactTextString(m) }
func (*AssetMetaInfo) ProtoMessage()    {}
func (*AssetMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15fd74ac3c1b80, []int{1}
}

func (m *AssetMetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetMetaInfo.Unmarshal(m, b)
}
func (m *AssetMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetMetaInfo.Marshal(b, m, deterministic)
}
func (m *AssetMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetMetaInfo.Merge(m, src)
}
func (m *AssetMetaInfo) XXX_Size() int {
	return xxx_messageInfo_AssetMetaInfo.Size(m)
}
func (m *AssetMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AssetMetaInfo proto.InternalMessageInfo

func (m *AssetMetaInfo) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *AssetMetaInfo) GetCoverImageUrl() string {
	if m != nil {
		return m.CoverImageUrl
	}
	return ""
}

func (m *AssetMetaInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AssetMetaInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AssetMetaInfo) GetTeaser() string {
	if m != nil {
		return m.Teaser
	}
	return ""
}

func (m *AssetMetaInfo) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *AssetMetaInfo) GetEventUrl() string {
	if m != nil {
		return m.EventUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Asset)(nil), "cc.entity.v1.Asset")
	proto.RegisterType((*AssetMetaInfo)(nil), "cc.entity.v1.AssetMetaInfo")
}

func init() { proto.RegisterFile("entity/v1/asset.proto", fileDescriptor_4c15fd74ac3c1b80) }

var fileDescriptor_4c15fd74ac3c1b80 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdd, 0xaa, 0xd3, 0x40,
	0x14, 0x85, 0x49, 0xda, 0xa6, 0x27, 0xbb, 0x3d, 0x2a, 0x83, 0x3f, 0x81, 0x83, 0x18, 0x7b, 0x21,
	0xbd, 0x4a, 0x89, 0x3e, 0x41, 0x5b, 0x7a, 0xd1, 0x0b, 0xa5, 0x04, 0x5b, 0x44, 0x0a, 0x61, 0x3a,
	0xd9, 0xc6, 0xc1, 0xfc, 0x94, 0xc9, 0x6e, 0xc0, 0xd7, 0xf1, 0xd2, 0x47, 0x11, 0x9f, 0xc0, 0xa7,
	0x91, 0xec, 0x49, 0xe1, 0xf4, 0x6e, 0xaf, 0xb5, 0x76, 0xc2, 0xfa, 0x66, 0x06, 0x5e, 0x60, 0x45,
	0x9a, 0x7e, 0x2e, 0xda, 0x78, 0x21, 0x9b, 0x06, 0x29, 0x3a, 0x9b, 0x9a, 0x6a, 0x31, 0x55, 0x2a,
	0xb2, 0x49, 0xd4, 0xc6, 0xb3, 0x7f, 0x0e, 0x8c, 0x96, 0x5d, 0x2a, 0x9e, 0x80, 0xab, 0xb3, 0xc0,
	0x09, 0x9d, 0xb9, 0x9f, 0xb8, 0x3a, 0x13, 0xaf, 0x60, 0x2c, 0x55, 0x91, 0x92, 0xcc, 0x03, 0x97,
	0x4d, 0x4f, 0xaa, 0xe2, 0xb3, 0xcc, 0xc5, 0x1b, 0x98, 0x94, 0x68, 0xd4, 0x77, 0x59, 0x51, 0xaa,
	0xb3, 0x60, 0xc0, 0x21, 0x5c, 0xad, 0x6d, 0x26, 0xde, 0xc2, 0x34, 0xc3, 0x46, 0x19, 0x7d, 0xc2,
	0xf4, 0x62, 0x8a, 0x60, 0xc8, 0x1b, 0x93, 0xab, 0xb7, 0x37, 0x85, 0x78, 0x0e, 0xa3, 0xb3, 0xd1,
	0x0a, 0x83, 0x51, 0xe8, 0xcc, 0x07, 0x89, 0x15, 0x62, 0x01, 0xc3, 0x12, 0x49, 0x06, 0x5e, 0xe8,
	0xcc, 0x27, 0xef, 0x1f, 0xa2, 0xc7, 0x4d, 0x23, 0x6e, 0xf9, 0x11, 0x49, 0x6e, 0xab, 0x6f, 0x75,
	0xc2, 0x8b, 0xe2, 0x35, 0x80, 0x32, 0x28, 0x09, 0xb3, 0x54, 0x52, 0x30, 0xe6, 0x7f, 0xf9, 0xbd,
	0xb3, 0xa4, 0xd9, 0x5f, 0x07, 0xee, 0x6f, 0x3e, 0x13, 0x02, 0x86, 0x3f, 0x74, 0x75, 0xc5, 0xe4,
	0x59, 0xbc, 0x83, 0xa7, 0xaa, 0x6e, 0xd1, 0xa4, 0xba, 0x94, 0xb9, 0x6d, 0x6c, 0x81, 0xef, 0xd9,
	0xde, 0x76, 0x6e, 0xdf, 0x99, 0x34, 0x15, 0xd8, 0x13, 0x5b, 0x21, 0x42, 0xe8, 0xc1, 0xce, 0xa4,
	0xeb, 0xea, 0x96, 0x95, 0x2d, 0xf1, 0x12, 0x3c, 0x42, 0xd9, 0xa0, 0x61, 0x58, 0x3f, 0xe9, 0x55,
	0xd7, 0xa5, 0x29, 0x2e, 0x39, 0xd3, 0xfa, 0x09, 0xcf, 0xe2, 0x01, 0x7c, 0x6c, 0xb1, 0x22, 0x6e,
	0x31, 0xe6, 0xe0, 0x8e, 0x8d, 0xbd, 0x29, 0x56, 0x9f, 0xe0, 0x99, 0xaa, 0xcb, 0x9b, 0x53, 0x59,
	0x01, 0xf3, 0xed, 0xba, 0x9b, 0xdd, 0x39, 0x5f, 0xef, 0x6c, 0xd0, 0xc6, 0xbf, 0xdc, 0xc1, 0x7a,
	0xf3, 0xe5, 0xb7, 0x3b, 0x5d, 0xab, 0x68, 0x63, 0x97, 0x0f, 0xf1, 0x9f, 0x4e, 0x1e, 0xad, 0x3c,
	0x1e, 0xe2, 0x93, 0xc7, 0x0f, 0xe2, 0xc3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xc7, 0x9a,
	0x51, 0x29, 0x02, 0x00, 0x00,
}
