// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/v1/transaction.proto

package entityv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Payment transaction.
type Payment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	TransactionId        string   `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_75eb51160df163d2, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Payment) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Payment) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

// Transaction.
type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DescribeUrls         []string `protobuf:"bytes,6,rep,name=describe_urls,json=describeUrls,proto3" json:"describe_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_75eb51160df163d2, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Transaction) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Transaction) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Transaction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Transaction) GetDescribeUrls() []string {
	if m != nil {
		return m.DescribeUrls
	}
	return nil
}

func init() {
	proto.RegisterType((*Payment)(nil), "cc.entity.v1.Payment")
	proto.RegisterType((*Transaction)(nil), "cc.entity.v1.Transaction")
}

func init() { proto.RegisterFile("entity/v1/transaction.proto", fileDescriptor_75eb51160df163d2) }

var fileDescriptor_75eb51160df163d2 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xd1, 0x6a, 0xf2, 0x30,
	0x14, 0xc7, 0x69, 0xfa, 0xd9, 0x6a, 0xbe, 0x2a, 0x12, 0xc6, 0xd6, 0xb1, 0x9b, 0xe2, 0x18, 0xf4,
	0xaa, 0x52, 0xf6, 0x06, 0x8a, 0x17, 0xbd, 0x2b, 0xc5, 0xc9, 0x18, 0x82, 0xc4, 0x24, 0xb0, 0x80,
	0x6d, 0x4a, 0x92, 0x16, 0x7c, 0x9d, 0xb1, 0xab, 0x3d, 0xca, 0x9e, 0x6a, 0x24, 0x51, 0x56, 0xd8,
	0xe5, 0xef, 0x77, 0x4e, 0xce, 0xff, 0x70, 0x02, 0x1f, 0x58, 0xa3, 0xb9, 0x3e, 0x2f, 0xfb, 0x7c,
	0xa9, 0x25, 0x6e, 0x14, 0x26, 0x9a, 0x8b, 0x26, 0x6b, 0xa5, 0xd0, 0x02, 0x45, 0x84, 0x64, 0xae,
	0x9e, 0xf5, 0xf9, 0xa2, 0x85, 0x61, 0x89, 0xcf, 0x35, 0x6b, 0x34, 0x9a, 0x41, 0xc0, 0x69, 0xec,
	0x25, 0x5e, 0x3a, 0xa9, 0x00, 0xa7, 0xe8, 0x16, 0x06, 0xb8, 0x16, 0x5d, 0xa3, 0x63, 0x90, 0x78,
	0xa9, 0x5f, 0x5d, 0xc8, 0xf8, 0x9a, 0xe9, 0x77, 0x41, 0x63, 0xdf, 0xf6, 0x5e, 0x08, 0x3d, 0xc1,
	0xd9, 0x20, 0xed, 0xc0, 0x69, 0xfc, 0xcf, 0xd6, 0xa7, 0x03, 0x5b, 0xd0, 0xc5, 0xa7, 0x07, 0xff,
	0x6f, 0x7f, 0xcd, 0x9f, 0xd8, 0x7b, 0x38, 0xc6, 0x4a, 0x31, 0x6d, 0x06, 0x00, 0x6b, 0x43, 0xcb,
	0x85, 0xdd, 0x48, 0x69, 0xac, 0x3b, 0x75, 0x4d, 0x76, 0x84, 0x6e, 0xe0, 0xa8, 0x95, 0x9c, 0x30,
	0x1b, 0xe8, 0x57, 0x0e, 0xd0, 0x1d, 0x0c, 0x3b, 0xc5, 0xa4, 0x99, 0x33, 0x72, 0xed, 0x06, 0x0b,
	0x8a, 0x1e, 0xe1, 0x94, 0x32, 0x45, 0x24, 0x3f, 0xb2, 0x43, 0x27, 0x4f, 0x2a, 0x0e, 0x12, 0x3f,
	0x9d, 0x54, 0xd1, 0x55, 0xbe, 0xc8, 0x93, 0x5a, 0x6d, 0xe1, 0x9c, 0x88, 0x3a, 0x1b, 0x1e, 0x6b,
	0x35, 0x1f, 0xec, 0x5d, 0x9a, 0x63, 0x96, 0xde, 0xdb, 0xd8, 0x95, 0xfb, 0xfc, 0x03, 0xf8, 0xeb,
	0xcd, 0xeb, 0x17, 0x88, 0xd6, 0x24, 0xdb, 0xb8, 0x27, 0xbb, 0xfc, 0xdb, 0xe0, 0xde, 0xe1, 0x7e,
	0x97, 0x1f, 0x03, 0xfb, 0x07, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x24, 0x18, 0xa3,
	0xa2, 0x01, 0x00, 0x00,
}
