// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endpoint/v1/shio_admin_api.proto

package endpointv1

import (
	context "context"
	fmt "fmt"
	v1 "github.com/digithun/shio/packages/admin/api/pkg/entity/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Session              *v1.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSession() *v1.Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "cc.endpoint.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "cc.endpoint.v1.LoginResponse")
}

func init() { proto.RegisterFile("endpoint/v1/shio_admin_api.proto", fileDescriptor_0ec0e0f6fa1fb808) }

var fileDescriptor_0ec0e0f6fa1fb808 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xcd, 0x4b, 0x29,
	0xc8, 0xcf, 0xcc, 0x2b, 0xd1, 0x2f, 0x33, 0xd4, 0x2f, 0xce, 0xc8, 0xcc, 0x8f, 0x4f, 0x4c, 0xc9,
	0xcd, 0xcc, 0x8b, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0x4e,
	0xd6, 0x83, 0x29, 0xd2, 0x2b, 0x33, 0x94, 0x12, 0x4f, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x04, 0xab,
	0x4f, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x83, 0x28, 0x94, 0x12, 0x41, 0x48, 0x94, 0x16, 0xa7, 0x16,
	0x41, 0x44, 0x95, 0x1c, 0xb8, 0x78, 0x7c, 0xf2, 0xd3, 0x33, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0x82, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14,
	0x09, 0x26, 0xb0, 0x04, 0x9c, 0xaf, 0xe4, 0xc0, 0xc5, 0x0b, 0x35, 0xa1, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x55, 0x48, 0x9f, 0x8b, 0x1d, 0x6a, 0x33, 0xd8, 0x10, 0x6e, 0x23, 0x51, 0x3d, 0xb0, 0x1b,
	0x41, 0xb6, 0xeb, 0x95, 0x19, 0xea, 0x05, 0x43, 0x24, 0x83, 0x60, 0xaa, 0x8c, 0x42, 0xb8, 0x78,
	0x82, 0x33, 0x32, 0xf3, 0x1d, 0x41, 0x3e, 0x73, 0x0c, 0xf0, 0x14, 0x72, 0xe1, 0x62, 0x05, 0x9b,
	0x28, 0x24, 0xa3, 0x87, 0xea, 0x39, 0x3d, 0x64, 0xa7, 0x4a, 0xc9, 0xe2, 0x90, 0x85, 0x38, 0xc3,
	0x29, 0x96, 0x4b, 0x28, 0x39, 0x3f, 0x17, 0x4d, 0x8d, 0x93, 0x20, 0xc2, 0xa6, 0x82, 0xcc, 0x00,
	0x50, 0x10, 0x04, 0x30, 0x46, 0x71, 0xc1, 0x54, 0x94, 0x19, 0x2e, 0x62, 0x62, 0x76, 0x76, 0x8d,
	0x58, 0xc5, 0xc4, 0xe7, 0x9c, 0xac, 0xe7, 0x0a, 0xd3, 0x17, 0x66, 0x78, 0x0a, 0x24, 0x10, 0x03,
	0x13, 0x88, 0x09, 0x33, 0x4c, 0x62, 0x03, 0x87, 0x9f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0xe6, 0x0e, 0x5c, 0xa2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShioAdminAPIClient is the client API for ShioAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShioAdminAPIClient interface {
	// Login Endpoint.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type shioAdminAPIClient struct {
	cc *grpc.ClientConn
}

func NewShioAdminAPIClient(cc *grpc.ClientConn) ShioAdminAPIClient {
	return &shioAdminAPIClient{cc}
}

func (c *shioAdminAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/cc.endpoint.v1.ShioAdminAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShioAdminAPIServer is the server API for ShioAdminAPI service.
type ShioAdminAPIServer interface {
	// Login Endpoint.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedShioAdminAPIServer can be embedded to have forward compatible implementations.
type UnimplementedShioAdminAPIServer struct {
}

func (*UnimplementedShioAdminAPIServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterShioAdminAPIServer(s *grpc.Server, srv ShioAdminAPIServer) {
	s.RegisterService(&_ShioAdminAPI_serviceDesc, srv)
}

func _ShioAdminAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioAdminAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cc.endpoint.v1.ShioAdminAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioAdminAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShioAdminAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cc.endpoint.v1.ShioAdminAPI",
	HandlerType: (*ShioAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ShioAdminAPI_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endpoint/v1/shio_admin_api.proto",
}
