// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endpoint/v1/shio_admin_api.proto

package endpointv1

import (
	context "context"
	fmt "fmt"
	v1 "github.com/digithun/shio/admin_api/pkg/entity/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Session              *v1.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSession() *v1.Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type GetAssetListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetListRequest) Reset()         { *m = GetAssetListRequest{} }
func (m *GetAssetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssetListRequest) ProtoMessage()    {}
func (*GetAssetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{2}
}

func (m *GetAssetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetListRequest.Unmarshal(m, b)
}
func (m *GetAssetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetListRequest.Marshal(b, m, deterministic)
}
func (m *GetAssetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetListRequest.Merge(m, src)
}
func (m *GetAssetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssetListRequest.Size(m)
}
func (m *GetAssetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetListRequest proto.InternalMessageInfo

type GetAssetListResponse struct {
	List                 []*v1.Asset `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAssetListResponse) Reset()         { *m = GetAssetListResponse{} }
func (m *GetAssetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssetListResponse) ProtoMessage()    {}
func (*GetAssetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{3}
}

func (m *GetAssetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetListResponse.Unmarshal(m, b)
}
func (m *GetAssetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetListResponse.Marshal(b, m, deterministic)
}
func (m *GetAssetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetListResponse.Merge(m, src)
}
func (m *GetAssetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAssetListResponse.Size(m)
}
func (m *GetAssetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetListResponse proto.InternalMessageInfo

func (m *GetAssetListResponse) GetList() []*v1.Asset {
	if m != nil {
		return m.List
	}
	return nil
}

type GetTransactionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionListRequest) Reset()         { *m = GetTransactionListRequest{} }
func (m *GetTransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListRequest) ProtoMessage()    {}
func (*GetTransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{4}
}

func (m *GetTransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListRequest.Unmarshal(m, b)
}
func (m *GetTransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListRequest.Merge(m, src)
}
func (m *GetTransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListRequest.Size(m)
}
func (m *GetTransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListRequest proto.InternalMessageInfo

type GetTransactionListResponse struct {
	List                 []*v1.Transaction `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetTransactionListResponse) Reset()         { *m = GetTransactionListResponse{} }
func (m *GetTransactionListResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListResponse) ProtoMessage()    {}
func (*GetTransactionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0e0f6fa1fb808, []int{5}
}

func (m *GetTransactionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListResponse.Unmarshal(m, b)
}
func (m *GetTransactionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListResponse.Merge(m, src)
}
func (m *GetTransactionListResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListResponse.Size(m)
}
func (m *GetTransactionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListResponse proto.InternalMessageInfo

func (m *GetTransactionListResponse) GetList() []*v1.Transaction {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "cc.endpoint.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "cc.endpoint.v1.LoginResponse")
	proto.RegisterType((*GetAssetListRequest)(nil), "cc.endpoint.v1.GetAssetListRequest")
	proto.RegisterType((*GetAssetListResponse)(nil), "cc.endpoint.v1.GetAssetListResponse")
	proto.RegisterType((*GetTransactionListRequest)(nil), "cc.endpoint.v1.GetTransactionListRequest")
	proto.RegisterType((*GetTransactionListResponse)(nil), "cc.endpoint.v1.GetTransactionListResponse")
}

func init() { proto.RegisterFile("endpoint/v1/shio_admin_api.proto", fileDescriptor_0ec0e0f6fa1fb808) }

var fileDescriptor_0ec0e0f6fa1fb808 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x8e, 0xd2, 0x40,
	0x18, 0x4d, 0x8b, 0xf8, 0xf3, 0x81, 0x24, 0x0e, 0x10, 0xa1, 0x68, 0x42, 0xaa, 0x89, 0x68, 0xe2,
	0x90, 0xe2, 0x03, 0xc8, 0x8f, 0x84, 0x18, 0xb9, 0x20, 0xc5, 0x10, 0x35, 0x18, 0x52, 0xcb, 0x44,
	0x26, 0xc2, 0x4c, 0xed, 0x0c, 0x35, 0xbe, 0xcb, 0x5e, 0xed, 0xe5, 0x3e, 0xca, 0x3e, 0xd5, 0xa6,
	0xed, 0x74, 0xdb, 0xb2, 0xdd, 0xcd, 0x5e, 0xce, 0x39, 0xe7, 0x3b, 0x67, 0xbe, 0x33, 0x03, 0x5d,
	0xc2, 0xb6, 0x1e, 0xa7, 0x4c, 0xf6, 0x03, 0xab, 0x2f, 0x76, 0x94, 0x6f, 0x9c, 0xed, 0x81, 0xb2,
	0x8d, 0xe3, 0x51, 0xec, 0xf9, 0x5c, 0x72, 0x54, 0x73, 0x5d, 0x9c, 0x88, 0x70, 0x60, 0x19, 0x4d,
	0xc2, 0x24, 0x95, 0xff, 0x43, 0xbd, 0x23, 0x04, 0x91, 0xb1, 0xcc, 0x78, 0x9e, 0xc2, 0x82, 0x08,
	0x41, 0x39, 0x53, 0x44, 0x27, 0x25, 0xa4, 0xef, 0x30, 0xe1, 0xb8, 0x32, 0x25, 0x1b, 0x29, 0x79,
	0x14, 0xc4, 0x8f, 0x51, 0x73, 0x08, 0xd5, 0x39, 0xff, 0x4d, 0x99, 0x4d, 0xfe, 0x1e, 0x89, 0x90,
	0xa8, 0x01, 0x65, 0x72, 0x70, 0xe8, 0xbe, 0xa5, 0x75, 0xb5, 0xde, 0x13, 0x3b, 0x3e, 0x20, 0x03,
	0x1e, 0x7b, 0x8e, 0x10, 0xff, 0xb8, 0xbf, 0x6d, 0xe9, 0x11, 0x71, 0x7d, 0x36, 0x87, 0xf0, 0x54,
	0x39, 0x08, 0x8f, 0x33, 0x41, 0x50, 0x1f, 0x1e, 0xa9, 0x6b, 0x45, 0x26, 0x95, 0x41, 0x13, 0x47,
	0x7b, 0x85, 0xe9, 0x38, 0xb0, 0xf0, 0x32, 0x26, 0xed, 0x44, 0x65, 0x36, 0xa1, 0x3e, 0x23, 0x72,
	0x14, 0x6e, 0x38, 0xa7, 0x42, 0xaa, 0xab, 0x98, 0x1f, 0xa1, 0x91, 0x87, 0x95, 0xff, 0x1b, 0x78,
	0xb0, 0xa7, 0x42, 0xb6, 0xb4, 0x6e, 0xa9, 0x57, 0x19, 0xd4, 0xf3, 0xe6, 0x91, 0xdc, 0x8e, 0x04,
	0x66, 0x07, 0xda, 0x33, 0x22, 0xbf, 0xa6, 0x4d, 0x64, 0xdd, 0xbf, 0x80, 0x51, 0x44, 0xaa, 0x8c,
	0xf7, 0xb9, 0x8c, 0x76, 0x3e, 0x23, 0x33, 0x14, 0x27, 0x0d, 0xce, 0x74, 0xa8, 0x2e, 0x77, 0x94,
	0x8f, 0xc2, 0x07, 0x1d, 0x2d, 0x3e, 0xa3, 0x4f, 0x50, 0x8e, 0x4a, 0x41, 0x2f, 0x70, 0xfe, 0x4d,
	0x71, 0xb6, 0x6d, 0xe3, 0xe5, 0x2d, 0xac, 0xba, 0xc5, 0x77, 0xa8, 0x66, 0x1b, 0x40, 0xaf, 0x4e,
	0xe5, 0x05, 0xb5, 0x19, 0xaf, 0xef, 0x16, 0x29, 0xeb, 0x3f, 0x80, 0x6e, 0xae, 0x8f, 0xde, 0x16,
	0xcc, 0x16, 0xf7, 0x67, 0xbc, 0xbb, 0x8f, 0x34, 0x0e, 0x1b, 0xff, 0x04, 0xe4, 0xf2, 0xc3, 0xc9,
	0xc0, 0xf8, 0x59, 0xda, 0x98, 0x47, 0x17, 0xe1, 0x6f, 0x5c, 0x68, 0x3f, 0x20, 0x51, 0x04, 0xd6,
	0xb9, 0x5e, 0x9a, 0x4c, 0xbf, 0x5d, 0xe8, 0xb5, 0x89, 0x8b, 0xa7, 0xc9, 0xdc, 0xca, 0xba, 0x0c,
	0x81, 0x75, 0x02, 0xac, 0x57, 0xd6, 0xaf, 0x87, 0xd1, 0x57, 0xfe, 0x70, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xab, 0xd4, 0x20, 0x61, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShioAdminAPIClient is the client API for ShioAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShioAdminAPIClient interface {
	// Login Endpoint.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// GetAssetList.
	GetAssetList(ctx context.Context, in *GetAssetListRequest, opts ...grpc.CallOption) (*GetAssetListResponse, error)
	// GetTransactionList.
	GetTransactionList(ctx context.Context, in *GetTransactionListRequest, opts ...grpc.CallOption) (*GetTransactionListResponse, error)
}

type shioAdminAPIClient struct {
	cc *grpc.ClientConn
}

func NewShioAdminAPIClient(cc *grpc.ClientConn) ShioAdminAPIClient {
	return &shioAdminAPIClient{cc}
}

func (c *shioAdminAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/cc.endpoint.v1.ShioAdminAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioAdminAPIClient) GetAssetList(ctx context.Context, in *GetAssetListRequest, opts ...grpc.CallOption) (*GetAssetListResponse, error) {
	out := new(GetAssetListResponse)
	err := c.cc.Invoke(ctx, "/cc.endpoint.v1.ShioAdminAPI/GetAssetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioAdminAPIClient) GetTransactionList(ctx context.Context, in *GetTransactionListRequest, opts ...grpc.CallOption) (*GetTransactionListResponse, error) {
	out := new(GetTransactionListResponse)
	err := c.cc.Invoke(ctx, "/cc.endpoint.v1.ShioAdminAPI/GetTransactionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShioAdminAPIServer is the server API for ShioAdminAPI service.
type ShioAdminAPIServer interface {
	// Login Endpoint.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// GetAssetList.
	GetAssetList(context.Context, *GetAssetListRequest) (*GetAssetListResponse, error)
	// GetTransactionList.
	GetTransactionList(context.Context, *GetTransactionListRequest) (*GetTransactionListResponse, error)
}

// UnimplementedShioAdminAPIServer can be embedded to have forward compatible implementations.
type UnimplementedShioAdminAPIServer struct {
}

func (*UnimplementedShioAdminAPIServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedShioAdminAPIServer) GetAssetList(ctx context.Context, req *GetAssetListRequest) (*GetAssetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetList not implemented")
}
func (*UnimplementedShioAdminAPIServer) GetTransactionList(ctx context.Context, req *GetTransactionListRequest) (*GetTransactionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionList not implemented")
}

func RegisterShioAdminAPIServer(s *grpc.Server, srv ShioAdminAPIServer) {
	s.RegisterService(&_ShioAdminAPI_serviceDesc, srv)
}

func _ShioAdminAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioAdminAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cc.endpoint.v1.ShioAdminAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioAdminAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioAdminAPI_GetAssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioAdminAPIServer).GetAssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cc.endpoint.v1.ShioAdminAPI/GetAssetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioAdminAPIServer).GetAssetList(ctx, req.(*GetAssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioAdminAPI_GetTransactionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioAdminAPIServer).GetTransactionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cc.endpoint.v1.ShioAdminAPI/GetTransactionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioAdminAPIServer).GetTransactionList(ctx, req.(*GetTransactionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShioAdminAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cc.endpoint.v1.ShioAdminAPI",
	HandlerType: (*ShioAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ShioAdminAPI_Login_Handler,
		},
		{
			MethodName: "GetAssetList",
			Handler:    _ShioAdminAPI_GetAssetList_Handler,
		},
		{
			MethodName: "GetTransactionList",
			Handler:    _ShioAdminAPI_GetTransactionList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endpoint/v1/shio_admin_api.proto",
}
